### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/bace/rdkfp1-7_512.npz'

### ISSUE THREAD

**Issue by ZexiChen502** [lihan97/KPGT#10]
Very interesting work, but I encountered the following error while extracting features, looking forward to your reply.

python extract_features.py --config base --model_path ../models/pretrained/base/base.pth --data_path ../datasets/ --dataset bace
Using backend: pytorch
Traceback (most recent call last):
  File "extract_features.py", line 61, in <module>
    extract_features(args)
  File "extract_features.py", line 30, in extract_features
    mol_dataset = MoleculeDataset(root_path=args.data_path, dataset = args.dataset, dataset_type=None)
  File "../src/data/finetune_dataset.py", line 24, in __init__
    fps = torch.from_numpy(sps.load_npz(ecfp_path).todense().astype(np.float32))
  File "/sibcb1/chenluonanlab8/chenzexi/anaconda3/envs/KPGT/lib/python3.7/site-packages/scipy/sparse/_matrix_io.py", line 123, in load_npz
    with np.load(file, **PICKLE_KWARGS) as loaded:
  File "/sibcb1/chenluonanlab8/chenzexi/anaconda3/envs/KPGT/lib/python3.7/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '../datasets/bace/rdkfp1-7_512.npz'

**Comment by ZexiChen502** [comment]
Ok, I forgot to perform this step：python preprocess_downstream_dataset.py --data_path ../datasets/ --dataset bace
