### ISSUE TITLE
Code and model weights for ablation experiments

### ISSUE THREAD

**Issue by DonghaiZHAO-ZJU** [lihan97/KPGT#14]
I have evaluated your model with different ADMET datasets and found that your model performs very well(best), now I would like to do some ablation experiments to explore what exactly plays a key role for my datasets in your model architecture, can you provide the code and model weights for the ablation experiments? I would be grateful if you could provide.

**Comment by lihan97** [comment]
Thank you for your interest in our model and for sharing your positive evaluation results! We're glad to hear that it performed well.

Regarding the ablation experiments, we did not retain the specific codes and model weights used during our ablation studies. However, all necessary details regarding the architecture and key components explored in the ablation can be found in our manuscript. We recommend referring to the manuscript to understand the key elements of the model and how they contribute to performance.

**Comment by DonghaiZHAO-ZJU** [comment]
在github上提供的代码，有体现您在文中提到的微调策略吗？

**Comment by lihan97** [comment]
> 在github上提供的代码，有体现您在文中提到的微调策略吗？

有的，运行finetune.py时可以通过设置参数 --use_flag/--use_llrd/--use_l2sp/--use_reinit调用不同的微调策略。

**Comment by abc1k** [comment]
谢谢您，我在跑这一版代码的时候又遇到一个问题：
Traceback (most recent call last):
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 236, in <module>
    finetune(args)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 231, in finetune
    best_train, best_val, best_test = trainer.fit(model, train_loader, val_loader, test_loader)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/../src/trainer/finetune_trainer.py", line 54, in fit
    self.train_epoch(model, train_loader, epoch)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/../src/trainer/finetune_trainer.py", line 35, in train_epoch
    predictions, labels = self._forward_epoch(model, batched_data)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/../src/trainer/finetune_trainer.py", line 26, in _forward_epoch
    predictions = model.forward_tune(g, ecfp, md, perturb)
TypeError: forward_tune() takes 4 positional arguments but 5 were given

您是不是忘了修改/src/model/light.py文件中forward_tune函数，这个参数在FLAG这种策略应该是有用到的吧。
另外，您有比较过这几种微调策略哪一种更好吗？我看文章好像没有阐述用了这几种微调策略之后会产生什么效果。

**Comment by abc1k** [comment]
def _forward_epoch(self, model, batched_data, perturb=None):
    (smiles, g, ecfp, md, labels) = batched_data
    ecfp = ecfp.to(self.device)
    md = md.to(self.device)
    g = g.to(self.device)
    labels = labels.to(self.device)
    
    # 将 perturb 传递给 forward_tune
    predictions = model.forward_tune(g, ecfp, md, perturb)
    return predictions, labels

def forward_tune(self, g, fp, md, perturb=None):
    indicators = g.ndata['vavn']  # 0 indicates normal atoms and nodes (triplets); -1 indicates virtual atoms; >=1 indicate virtual nodes 
    # Input
    node_h = self.node_emb(g.ndata['begin_end'], indicators)          
    edge_h = self.edge_emb(g.ndata['edge'], indicators)
    triplet_h = self.triplet_emb(node_h, edge_h, fp, md, indicators)

    # 应用 perturb 来调整 triplet_h 或 node_h / edge_h
    if perturb is not None:
        # 这里假设 perturb 用于调整节点特征
        triplet_h += perturb  # 或者根据具体需求进行调整

    # Model
    triplet_h = self.model(g, triplet_h)
    g.ndata['ht'] = triplet_h

    # Readout
    fp_vn = triplet_h[indicators == 1]
    md_vn = triplet_h[indicators == 2]
    g.remove_nodes(np.where(indicators.detach().cpu().numpy() >= 1)[0])
    readout = dgl.readout_nodes(g, 'ht', op=self.readout_mode)
    g_feats = torch.cat([fp_vn, md_vn, readout], dim=-1)

    # Predict
    return self.predictor(g_feats)
 我可以这样更改函数吗？

**Comment by DonghaiZHAO-ZJU** [comment]
新版代码遇到的问题：
Traceback (most recent call last):
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 236, in <module>
    finetune(args)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 231, in finetune
    best_train, best_val, best_test = trainer.fit(model, train_loader, val_loader, test_loader)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/../src/trainer/finetune_trainer.py", line 54, in fit
    self.train_epoch(model, train_loader, epoch)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/../src/trainer/finetune_trainer.py", line 35, in train_epoch
    predictions, labels = self._forward_epoch(model, batched_data)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/../src/trainer/finetune_trainer.py", line 26, in _forward_epoch
    predictions = model.forward_tune(g, ecfp, md, perturb)
TypeError: forward_tune() takes 4 positional arguments but 5 were given
您是不是忘了调整模型前向传播的代码？
![image](https://github.com/user-attachments/assets/a9abb14c-cca5-4acc-9f1f-f552eb84130e)
我可以这样修改吗？

**Comment by DonghaiZHAO-ZJU** [comment]
Traceback (most recent call last):
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 257, in <module>
    best_train, best_val, best_test, best_train1, best_val1, best_test1, best_train2, best_val2, best_test2 = finetune(args)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 231, in finetune
    model.model.mol_T_layers[layer + 1].initialize()
  File "/home/donghai/miniconda3/envs/KPGT1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TripletTransformer' object has no attribute 'initialize'
Traceback (most recent call last):
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 257, in <module>
    best_train, best_val, best_test, best_train1, best_val1, best_test1, best_train2, best_val2, best_test2 = finetune(args)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 231, in finetune
    model.model.mol_T_layers[layer + 1].initialize()
  File "/home/donghai/miniconda3/envs/KPGT1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TripletTransformer' object has no attribute 'initialize'
Traceback (most recent call last):
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 257, in <module>
    best_train, best_val, best_test, best_train1, best_val1, best_test1, best_train2, best_val2, best_test2 = finetune(args)
  File "/home/donghai/admet_models_validation/KPGT-main_new/scripts/finetune.py", line 231, in finetune
    model.model.mol_T_layers[layer + 1].initialize()
  File "/home/donghai/miniconda3/envs/KPGT1/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'TripletTransformer' object has no attribute 'initialize'

还有这种微调策略
